# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  # Security wrappers to mount fs as user
  #   security.wrappers = {
  #   mount.source = "${pkgs.utillinux}/bin/mount";
  #   umount.source = "${pkgs.utillinux}/bin/umount";
  #   "mount.nfs" = {
  #     setuid = true;
  #     owner = "lukaszpe";
  #     group = "users";
  #     source = "${pkgs.nfs-utils.out}/bin/mount.nfs";
  #   };
  # };
  #NFS Mounts
  fileSystems."/media/Skany"={
  device= "192.168.178.11:/mnt/udata/skany";
  fsType= "nfs";
  options=[
    "proto=tcp"
    "defaults"
    "users"
    "x-systemd.automount"
    "noauto"
    "_netdev"
    "x-systemd.after=network-online.target"
    "x-systemd.mount-timeout=10"
    ];
  };
  fileSystems."/media/ŁEPskiSerwer"={
  device= "192.168.178.12:/mnt/dane/dane";
  fsType= "nfs";
  options=[
    "proto=tcp"
    "defaults"
    "users"
    "x-systemd.automount"
    "noauto"
    "_netdev"
    "x-systemd.after=network-online.target"
    "x-systemd.mount-timeout=10"
    ];
  };

}
